### ISSUE TITLE
感觉1.4的Kotlin Version SAM还不错，项目里面好多用Lambda表达式写的都可以换成KSAM了。

### ISSUE THREAD

**Issue by Richyeoh** [enbandari/Kotlin1.4FeaturesSample#1]

**Comment by bennyhuo** [comment]
对的

--------------原始邮件--------------
发件人："泽被苍生 "<notifications@github.com&gt;;
发送时间：2020年3月25日(星期三) 中午12:19
收件人："enbandari/Kotlin1.4FeaturesSample" <Kotlin1.4FeaturesSample@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[enbandari/Kotlin1.4FeaturesSample] 感觉1.4的Kotlin Version SAM还不错，项目里面好多用Lambda表达式写的都可以换成KSAM了。 (#1)
-----------------------------------
